--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ColinHDev/CSkull
build-by-default: true
branches:
- main
projects:
  CSkull:
    path: ""
    libs:
    - src: poggit/libasynql/libasynql
      version: 4.1.0
...
